
server:
  port: 8888
spring:
  profiles:
    active: test
  application:
    name: microservice-config-client
eureka:
  instance:
    hostname: eureka8888.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8888.com/eureka/
