spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
      host: localhost
      port: 6379
